/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class GUIloginn extends javax.swing.JFrame {

    /**
     * Creates new form GUIloginn
     */
    public GUIloginn() {
        initComponents();
        setExtendedState(GUIloginn.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtmasuk1 = new javax.swing.JLabel();
        fieldemail = new javax.swing.JTextField();
        fieldpw = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 163, 221));
        jLabel3.setText("Belum punya akun?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 520, -1, -1));

        txtmasuk1.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtmasuk1.setForeground(new java.awt.Color(0, 51, 204));
        txtmasuk1.setText("Buat!");
        txtmasuk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtmasuk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmasuk1MouseClicked(evt);
            }
        });
        getContentPane().add(txtmasuk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 520, -1, -1));

        fieldemail.setBorder(null);
        fieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldemailActionPerformed(evt);
            }
        });
        getContentPane().add(fieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 380, 340, 30));

        fieldpw.setBorder(null);
        fieldpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpwActionPerformed(evt);
            }
        });
        getContentPane().add(fieldpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 462, 340, 30));

        btlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 17.png"))); // NOI18N
        btlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btloginMouseClicked(evt);
            }
        });
        getContentPane().add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 9.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldemailActionPerformed
        // TODO add your handling code here:
        if (fieldemail.getText().equals("")){
            fieldemail.setText("");
        }
    }//GEN-LAST:event_fieldemailActionPerformed

    private void fieldpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpwActionPerformed
        // TODO add your handling code here:
        if (fieldpw.getText().equals("")){
            fieldpw.setText("");
        }
    }//GEN-LAST:event_fieldpwActionPerformed

    private void txtmasuk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmasuk1MouseClicked
        // TODO add your handling code here:
        new GUIsignup().setVisible(true);
        dispose();
    }//GEN-LAST:event_txtmasuk1MouseClicked

    private void btloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btloginMouseClicked
        // TODO add your handling code here:
        login();
        
    }//GEN-LAST:event_btloginMouseClicked

    private void login(){
        PreparedStatement st;
        ResultSet rs;

        // Buat kueri SQL dengan tanda tanya sebagai placeholder
        String query = "SELECT * FROM signup WHERE email = ? AND password = ?";

        try {
            st = KoneksiKashoes.koneksikashoesdB().prepareStatement(query);

            // Setel nilai parameter menggunakan setter PreparedStatement
            st.setString(1, fieldemail.getText());
            st.setString(2, fieldpw.getText());

            rs = st.executeQuery();

            if (rs.next()) {
                // Kombinasi email dan kata sandi cocok dalam database
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                new GUIdashbord().setVisible(true);
                dispose();

            } else {
                // Kombinasi email dan kata sandi tidak cocok
                JOptionPane.showMessageDialog(rootPane, "Invalid Username or Password", "Login Error", JOptionPane.ERROR_MESSAGE);
                fieldpw.setText("");
                fieldemail.setText(""); // Anda mungkin ingin membersihkan isian email juga
                fieldemail.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace(); // Ini akan mencetak detail kesalahan ke konsol
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIloginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIloginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIloginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIloginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIloginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btlogin;
    private javax.swing.JTextField fieldemail;
    private javax.swing.JPasswordField fieldpw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtmasuk1;
    // End of variables declaration//GEN-END:variables
}
