/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class GUIlistorder extends javax.swing.JFrame {

    /**
     * Creates new form GUIlistorder
     */
    public GUIlistorder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        bteditR = new javax.swing.JLabel();
        bthapusR = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelrepaint = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bteditU = new javax.swing.JLabel();
        bthapusU = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelunyellowing = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldeepclean = new javax.swing.JTable();
        bteditD = new javax.swing.JLabel();
        bthapusD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(21, 152, 217));
        jLabel16.setText("REPAINT");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 220, -1, -1));

        bteditR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (2).png"))); // NOI18N
        getContentPane().add(bteditR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 210, -1, -1));

        bthapusR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (3).png"))); // NOI18N
        getContentPane().add(bthapusR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 210, -1, -1));

        tabelrepaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelrepaint);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 250, 510, 250));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teenyicons_home-solid.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(21, 152, 217));
        jLabel15.setText("UNYELLOWING");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

        bteditU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (2).png"))); // NOI18N
        getContentPane().add(bteditU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, -1, 20));

        bthapusU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (3).png"))); // NOI18N
        getContentPane().add(bthapusU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, -1, -1));

        tabelunyellowing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelunyellowing);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 510, 250));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 152, 217));
        jLabel14.setText("DEEP CLEAN");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel13.setText("DASHBOARD");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel8.setText("LIST ORDER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Mask group.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel2.setText("MANAGEMENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (1).png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/solar_logout-3-bold.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, -1, -1));

        tabeldeepclean.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldeepclean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldeepcleanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldeepclean);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 510, 250));

        bteditD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (2).png"))); // NOI18N
        bteditD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bteditD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bteditDMouseClicked(evt);
            }
        });
        getContentPane().add(bteditD, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, 20));

        bthapusD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Vector (3).png"))); // NOI18N
        bthapusD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bthapusD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthapusDMouseClicked(evt);
            }
        });
        getContentPane().add(bthapusD, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mdi_show.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 20.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(GUIlistorder.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda berhasil Logout");

        new GUIlogin().setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void tabeldeepcleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldeepcleanMouseClicked
        // TODO add your handling code here:
        try {
            java.sql.Connection kon = KoneksiKashoes.koneksikashoesdB();
            String sql = "SELECT * FROM deep_clean WHERE nama ='"+"'";
            Statement st = kon.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sql);
           
                    int bar = tabeldeepclean.getSelectedRow();
                       String a = tabeldeepclean.getValueAt(bar,0).toString();
                       String b = tabeldeepclean.getValueAt(bar,1).toString();
                       String c = tabeldeepclean.getValueAt(bar,2).toString();
                       String d = tabeldeepclean.getValueAt(bar,3).toString();
                       String e = tabeldeepclean.getValueAt(bar,4).toString();
                       String f = tabeldeepclean.getValueAt(bar,5).toString();
                       String g = tabeldeepclean.getValueAt(bar,6).toString();
                       
                      
                            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                

            }
        int bar = tabeldeepclean.getSelectedRow();
        String a = tabeldeepclean.getValueAt(bar,0).toString();
        String b = tabeldeepclean.getValueAt(bar,1).toString();
        String c = tabeldeepclean.getValueAt(bar,2).toString();
        String d = tabeldeepclean.getValueAt(bar,3).toString();
        String e = tabeldeepclean.getValueAt(bar,4).toString();
        String f = tabeldeepclean.getValueAt(bar,5).toString();
        String g = tabeldeepclean.getValueAt(bar,6).toString();

  
    }//GEN-LAST:event_tabeldeepcleanMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new GUIdashbord().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void bthapusDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthapusDMouseClicked
        // TODO add your handling code here:
        hapus();
        table();
        edit();
        
    }//GEN-LAST:event_bthapusDMouseClicked

    private void bteditDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bteditDMouseClicked
        // TODO add your handling code here:
        edit();
        table();
    }//GEN-LAST:event_bteditDMouseClicked

    private void table(){    
        
         
         Object header[] = {"nama","no_telp","alamat","jenis_sepatu","jumlah_sepatu","deskripsi_pesanan","tgl_masuk"};
         DefaultTableModel data = new DefaultTableModel(null,header);
         String sql_data = "SELECT nama,no_telp,alamat,jenis_sepatu,jumlah_sepatu,deskripsi_pesanan,tgl_masuk FROM deep_clean ORDER BY nama ASC";
         
         
         try{
             Connection kon = KoneksiKashoes.koneksikashoesdB();
             Statement st = kon.createStatement();
             ResultSet rs = st.executeQuery(sql_data);
             while(rs.next()){
                 String d1 = rs.getString(1);
                 String d2 = rs.getString(2);
                 String d3 = rs.getString(3);
                 String d4 = rs.getString(4);
                 String d5 = rs.getString(5);
                 String d6 = rs.getString(6);
                 String d7 = rs.getString(7);

                
                 
                 String d[] = {d1,d2,d3,d4,d5,d6,d7};
                 data.addRow(d);
                 
                 
             }
             
            tabeldeepclean.setModel(data);
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }
    private void edit() {
        try{
            Connection kon = KoneksiKashoes.koneksikashoesdB();
            Statement st = kon.createStatement();
           
                String sql_up = "UPDATE deep_clean SET nama='"
                        + "',no_telp='" 
                        + "',alamat='" 
                        + "',jenis_sepatu='"
                        + "',jumlah_sepatu='"
                        + "',deskripsi_pesanan='"
                        + "',tgl_masuk='" +"' WHERE nama='"+"'";
                st.execute(sql_up);
                JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
}



     private void hapus(){
        int update= JOptionPane.showOptionDialog(this,"apakah yakin hapus data?","Hapus Data",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
            if(update == JOptionPane.YES_OPTION){
            try{
                 Connection kon = KoneksiKashoes.koneksikashoesdB();
                 Statement st = kon.createStatement();
                 String sql_del = "DELETE from deep_clean WHERE nama='"+"'";
                 st.execute(sql_del);
                 JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                 table();
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
             }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIlistorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIlistorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIlistorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIlistorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIlistorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bteditD;
    private javax.swing.JLabel bteditR;
    private javax.swing.JLabel bteditU;
    private javax.swing.JLabel bthapusD;
    private javax.swing.JLabel bthapusR;
    private javax.swing.JLabel bthapusU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabeldeepclean;
    private javax.swing.JTable tabelrepaint;
    private javax.swing.JTable tabelunyellowing;
    // End of variables declaration//GEN-END:variables
}
