/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class GUIlogin extends javax.swing.JFrame {

    /**
     * Creates new form GUIlogin
     */
    public GUIlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btmasuk = new javax.swing.JLabel();
        fieldpasslogin = new javax.swing.JPasswordField();
        fieldnamalogin = new javax.swing.JTextField();
        txtdaftar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 163, 221));
        jLabel3.setText("Belum punya akun?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 520, -1, -1));

        btmasuk.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        btmasuk.setForeground(new java.awt.Color(0, 51, 204));
        btmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 17.png"))); // NOI18N
        btmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmasukMouseClicked(evt);
            }
        });
        getContentPane().add(btmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 530, -1, -1));

        fieldpasslogin.setBorder(null);
        fieldpasslogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldpasslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpassloginActionPerformed(evt);
            }
        });
        getContentPane().add(fieldpasslogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 460, 350, 30));

        fieldnamalogin.setBorder(null);
        fieldnamalogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldnamalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnamaloginActionPerformed(evt);
            }
        });
        getContentPane().add(fieldnamalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 380, 340, 30));

        txtdaftar1.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtdaftar1.setForeground(new java.awt.Color(0, 51, 204));
        txtdaftar1.setText("Daftar!");
        txtdaftar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtdaftar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdaftar1MouseClicked(evt);
            }
        });
        getContentPane().add(txtdaftar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 9.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(GUIlogin.MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_formWindowOpened

    private void btmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmasukMouseClicked
        // TODO add your handling code here:
       masuk(); 
    }//GEN-LAST:event_btmasukMouseClicked

    private void fieldpassloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpassloginActionPerformed
        // TODO add your handling code here:
        if (fieldpasslogin.getText().equals("")){
            fieldpasslogin.setText("");
        }
    }//GEN-LAST:event_fieldpassloginActionPerformed

    private void fieldnamaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnamaloginActionPerformed
        // TODO add your handling code here:
        if (fieldnamalogin.getText().equals("")){
            fieldnamalogin.setText("");
        }
    }//GEN-LAST:event_fieldnamaloginActionPerformed

    private void txtdaftar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdaftar1MouseClicked
        // TODO add your handling code here:
        new GUIsignup().setVisible(true);
        dispose();
    }//GEN-LAST:event_txtdaftar1MouseClicked

    private void masuk(){
         try {
            Connection kon = KoneksiKashoes.koneksikashoesdB();
            Statement st = kon.createStatement();

            String email = fieldnamalogin.getText();
            String nama = fieldnamalogin.getText();
            String password = fieldpasslogin.getText();

            // Perhatikan bahwa Anda hanya perlu memeriksa email dan password dalam query SQL.
            String sql = "SELECT * FROM signup WHERE email = ? || nama = ? AND password = ?";

            PreparedStatement preparedStatement = kon.prepareStatement(sql);
            preparedStatement.setString(1, email);
            preparedStatement.setString(1, nama);
            preparedStatement.setString(2, password);

            ResultSet r = preparedStatement.executeQuery();

            if (r.next()) {
                // Berhasil login
                JOptionPane.showMessageDialog(null, "Login Berhasil");

                // Buka GUIdashbord jika berhasil login
                GUIdashbord dashboard = new GUIdashbord();
                dashboard.setVisible(true);

                // Tutup jendela login jika diperlukan
                dispose();
            } else {
                // Email atau password salah
                JOptionPane.showMessageDialog(null, "Email atau Password Salah");
                fieldpasslogin.setText(""); // Kosongkan field password
                fieldpasslogin.requestFocus(); // Fokuskan kembali ke field password
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Tangani kesalahan database dengan mencetak informasi kesalahan
        }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btmasuk;
    private javax.swing.JTextField fieldnamalogin;
    private javax.swing.JPasswordField fieldpasslogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtdaftar1;
    // End of variables declaration//GEN-END:variables
}
