/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class GUIsignup extends javax.swing.JFrame {

    /**
     * Creates new form GUIlogin
     */
    public GUIsignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldemail = new javax.swing.JTextField();
        fieldnama = new javax.swing.JTextField();
        btdaftar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldpass = new javax.swing.JPasswordField();
        txtmasuk1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldemail.setBorder(null);
        fieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldemailActionPerformed(evt);
            }
        });
        getContentPane().add(fieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 380, 320, 30));

        fieldnama.setBorder(null);
        fieldnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnamaActionPerformed(evt);
            }
        });
        getContentPane().add(fieldnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 460, 320, 30));

        btdaftar.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        btdaftar.setForeground(new java.awt.Color(0, 51, 204));
        btdaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 18.png"))); // NOI18N
        btdaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btdaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdaftarMouseClicked(evt);
            }
        });
        getContentPane().add(btdaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 163, 221));
        jLabel3.setText("Sudah punya akun?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 610, -1, -1));

        fieldpass.setBorder(null);
        fieldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpassActionPerformed(evt);
            }
        });
        getContentPane().add(fieldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1249, 540, 350, 40));

        txtmasuk1.setFont(new java.awt.Font("Montserrat", 1, 10)); // NOI18N
        txtmasuk1.setForeground(new java.awt.Color(0, 51, 204));
        txtmasuk1.setText("Masuk");
        txtmasuk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtmasuk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmasuk1MouseClicked(evt);
            }
        });
        getContentPane().add(txtmasuk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 10.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(GUIsignup.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void fieldnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnamaActionPerformed
        // TODO add your handling code here:
         if (fieldnama.getText().equals("")){
             fieldnama.setText("");
         }
    }//GEN-LAST:event_fieldnamaActionPerformed

    private void fieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldemailActionPerformed
        // TODO add your handling code here:
       if (fieldemail.getText().equals("")){
             fieldemail.setText("");
         }
    }//GEN-LAST:event_fieldemailActionPerformed

    private void btdaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdaftarMouseClicked
        // TODO add your handling code here:
       tambah();
       clear();
       new GUIlogin().setVisible(true);
       dispose();
    }//GEN-LAST:event_btdaftarMouseClicked

    private void fieldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpassActionPerformed
        // TODO add your handling code here:
        if (fieldpass.getText().equals("")){
             fieldpass.setText("");
         }
    }//GEN-LAST:event_fieldpassActionPerformed

    private void txtmasuk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmasuk1MouseClicked
        // TODO add your handling code here:
        new GUIlogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_txtmasuk1MouseClicked

     private void tambah(){
     try{

            Connection kon = KoneksiKashoes.koneksikashoesdB();
            Statement st = kon.createStatement();

            PreparedStatement prs = kon.prepareStatement("INSERT INTO signup (email,nama,password) VALUES(?,?,?)"); 
            
            prs.setString(1, fieldemail.getText());
            prs.setString(2, fieldnama.getText());
            prs.setString(3, fieldpass.getText());
            prs.execute();
             JOptionPane.showMessageDialog(null, "Data Berhasil Di Masukan");
            }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           System.out.println(e.getMessage());
        }
    }
     private void clear(){
         fieldemail.setText("");
         fieldnama.setText("");
         fieldpass.setText("");
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btdaftar;
    private javax.swing.JTextField fieldemail;
    private javax.swing.JTextField fieldnama;
    private javax.swing.JPasswordField fieldpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtmasuk1;
    // End of variables declaration//GEN-END:variables
}
